version: '3.7'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
    ports:
      - '5431:5432'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
